name: Manual Release WRT
run-name: Manual Release WRT - ${{ inputs.model }}

on:
  # schedule:
  #   - cron: "0 4 * * 5"
  workflow_dispatch: 
    inputs:
      model:
        type: choice
        description: 'Model to release'
        required: true
        default: lk_ipq60xx_libwrt
        options:
          
          - lk_ipq60xx_immwrt

      

          
          

permissions:
  actions: write
  contents: write

jobs:
  release:
    name: Release ${{ github.event.inputs.model }}
    uses: ./.github/workflows/release_wrt.yml
    with:
      model: ${{ github.event.inputs.model }}
    secrets: inherit
